### ISSUE TITLE
Unwinding after catching SIGABRT

### ISSUE THREAD

**Issue by Foreveratu** [red-rocket-computing/backtrace#14]
I have written a small piece of code to test the library. 

The small piece of code is generating a SIGABRT an is catching it thanks to :

sigaction(SIGABRT, &sa, NULL);

the signal handler is then able to call backtrace_unwind function. 

Unfortunatelly the backtrace stopped at __pthread_kill_implementation.constprop and the library is not able to unwind further.

Do you know why the library is not able to do it ?

**Comment by sgstreet** [comment]
From the __pthread_kill_implementation comment I assume your application is running under Linux?  What is your architecture?  This library is designed and test for bare-metal 32-bit arm processors. Think Cortex-M class MCUs.

**Comment by Foreveratu** [comment]
My application is running under qemu-arm-static and I'm using a toolchain generated by myself with ct-ng (arm-unknown-linux-gnueabi-gcc).

Sorry for the misunderstanding.

**Comment by Foreveratu** [comment]
Thanks for all your explanations
