### ISSUE TITLE
_Unwind_Backtrace

### ISSUE THREAD

**Issue by Viatorus** [red-rocket-computing/backtrace#4]
Hello,

I wanted to ask why you don't use the function __Unwind_Backtrace_ defined in _unwind-arm-common.h_.
This function works very similar to this implementation and works on an STM32F4.

Another question:
After throwing an exception, which calls std::terminate, I cannot get a complete backtrace (neither with your implementation or with _Unwind_Backtrace).
Doing the exact same thing on a linux system, everything works fine. Do you know anything about this limitation?

**Comment by sgstreet** [comment]
This library is not intended for use in C++ program.  You might try GCC built-in exception handling for C++

**Comment by denravonska** [comment]
@Viatorus Did you ever find a solution for this? I have a similar issue where I can't get a complete backtrace after a hardfault, be it with this lib or with `_Unwind_Backtrace`.

**Comment by Viatorus** [comment]
No, not really. I still get these problems of incomplete backtraces, even for non hardfaults.

**Comment by denravonska** [comment]
I got this lib working now by using the "standard" hardfault handler recommended everywhere, and by feeding the stack pointer it resolves from MSP/PSP into `backtrace_unwind_from_frame`. This is a custom struct but it translates directly to the one found in this lib, except that `sp` has to be copied into this lib's `fp`.

```C
void prvGetRegistersFromStack(uint32_t *pulFaultStackAddress)
{
    struct RegisterFrame frame =
    {
        .r0 = pulFaultStackAddress[ 0 ],
        .r1 = pulFaultStackAddress[ 1 ],
        .r2 = pulFaultStackAddress[ 2 ],
        .r3 = pulFaultStackAddress[ 3 ],
        .r12 = pulFaultStackAddress[ 4 ],
        .lr = pulFaultStackAddress[ 5 ],
        .pc = pulFaultStackAddress[ 6 ],
        .psr = pulFaultStackAddress[ 7 ],
        // SP is copied to r0 below
        .sp = pulFaultStackAddress[ 0 ]
    };

    __NOP();
    HardFaultHook(&frame);
    NVIC_SystemReset();
}

void HardFault_Handler(void)
{
    __asm volatile
    (
        " tst lr, #4                                                \n"
        " ite eq                                                    \n"
        " mrseq r0, msp                                             \n"
        " mrsne r0, psp                                             \n"
        " ldr r1, [r0, #24]                                         \n"
        " ldr r2, handler2_address_const                            \n"
        " bx r2                                                     \n"
        " handler2_address_const: .word prvGetRegistersFromStack    \n"
    );
```

My hook then populates `backtrace_frame_t` and passes it to `backtrace_unwind_from_frame`.

```C++
    backtrace_frame_t _frame =
    {
        .fp = frame.sp, // Intentional, not a typo
        .sp = frame.sp,
        .lr = frame.lr,
        .pc = frame.pc
    };

    backtrace_t _buffer[8];
    int items = backtrace_unwind_from_frame(&_buffer[0], 8, _frame);
    for(int i=0; i<items; i++)
        buffer[i].address = _buffer[i].address;

    return items;
```

Hope it helps :)

This is on a Cortex M33, so YMMV.

Edit: I just noticed that `backtrace_unwind_from_frame` isn't available upstream. [This PR](https://github.com/red-rocket-computing/backtrace/pull/11) fixes that.
