### ISSUE TITLE
multiple definitions compilation errors

### ISSUE THREAD

**Issue by durka** [red-rocket-computing/backtrace#5]
The functions `__aeabi_unwind_cpp_pr0` etc in backtrace.c have a comment saying they prevent the linking of the same functions in libgcc, but I just get errors about that:

```
/usr/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/hard/libgcc.a(unwind-arm.o): In function `__aeabi_unwind_cpp_pr0':
unwind-arm.c:(.text+0x760): multiple definition of `__aeabi_unwind_cpp_pr0'
build/backtrace_backtrace.c.o:backtrace.c:(.text.__aeabi_unwind_cpp_pr0+0x0): first defined here
collect2: error: ld returned 1 exit status
```

**Comment by sgstreet** [comment]
Sorry for the huge delay. Can you post the complete link line?

**Comment by hansbinderup** [comment]
Because it's already done [here](https://elixir.bootlin.com/linux/latest/source/arch/arm/kernel/unwind.c#L37). This library is meant for C, so if using C++ you can either check for this compile time:

```c++
#ifndef __cplusplus
void __aeabi_unwind_cpp_pr0(void) {};
void __aeabi_unwind_cpp_pr1(void) {};
void __aeabi_unwind_cpp_pr2(void) {};
#endif
```

or simply remove them.
