### ISSUE TITLE
Bug: in backtrace.c 'pop under mask {r15-r12},{r11-r4}...' evaluating mask that is 0 by definition.

### ISSUE THREAD

**Issue by steven-buytaert** [red-rocket-computing/backtrace#7]
While handling that case, after the while loop, which stops when the mask is 0, the mask is by definition 0, and the writeback to the virtual stackpointer fails. Check the mask for 1 << (13 -4) *before* entering the while loop.

**Comment by sgstreet** [comment]
Better late the never, I guess
