### ISSUE TITLE
Only getting one level of backtrace

### ISSUE THREAD

**Issue by denravonska** [red-rocket-computing/backtrace#8]
I've been trying to get this lib working on Cortex-M33 as an alternative to `_Unwind_Backtrace` which doesn't return anything. This lib works slightly better, but it's only returning one level in the backtrace

```
00> Backtrace, 1 steps
00>    Addr: 0x800EF58
```

which points to `backtrace.h:75` in my case:
```
	/* Let it rip */
	return _backtrace_unwind(buffer, size, &frame);
```

I have enabled the compile flags specified in the README. Is there anything else I should watch out for? (trying to debug but gdb-server shuts itself down when hitting a breakpoint).

`arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)`

**Comment by sgstreet** [comment]
Uhmm, not sure what is going on here. With the caveat that I have not tested the library on a armv8-m micro, I suspect a problem with the executable link.  Can you post the linker script you used and a matching linker map file `(-Wl,--cref -Wl,-Map,"test.map")` as well as the exact compiler command you used to build and link your executable?

You might review

 ```
__exidx_start /* Pointing to the start of the unwind index table */
__exidx_end   /* Pointing to the end of the unwind index table */
```

output in you linker map file.  Whose chip and board are you using?  Do you know if there is a QEMU board which uses a M33?

**Comment by denravonska** [comment]
After doing some digging it turned out that, due to the way our buildsystem is setup, the build flags were only applied to the application and not its dependencies. After fixing that I can get the full trace.

Thanks for helping though :)
