### ISSUE TITLE
cortex m-4 support

### ISSUE THREAD

**Issue by MadNugget** [red-rocket-computing/backtrace#9]
I have a project using a Microchip SAM4E.  I experience a crash via memory access violation when the the line at 165 in backtrace.c tries to de-reference an out of range location.  In this case 0xa5a5a5a5.  This is while testing this library calling backtrace_unwind in main().  If I add a new if statement in _backtrace_unwind as so, to catch:
'''
 if (frame->fp == 0xa5a5a5a5 || frame->fp == 0x00000000)
   // end of stack
'''
This prevents the future crash further on at line 165
Then all seems to work.  My question then, is this compatible with ARM m-4, and is this the correct way to detect if then end of stack has been reached? 

EDIT:  Essentially, if the frame pointer going into the unwind functions is NULL or out of memory range, in this case 0xa5a5a5a5,  then later on in the unwind_execute_instruction() function, when vsp is de-referenced, the crash or memory fault triggers.

**Comment by sgstreet** [comment]
Very sorry for ignoring this, real work interference. So your frame pointer is undefined at the end of you stack. I have found that you need to initialize the end of a thread stack to insure the the frame pointer is null.  You might also check your compiler flags to insure a frame pointer is really generated.
